spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      serviceZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
